$(function(){
    $('.detailpage').bxSlider({
        mode:'horizontal',
        auto:true,
        speed:700,
        pause:2500,
        pager:false,
        controls:false,
    })
})

$(function(){
    $('.image').bxSlider({
        mode:'horizontal',
        auto:true,
        speed:700,
        pause:2500,
        pager:false,
        controls:false,
    })
})
